INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME) VALUES ('Prabhas','Amar');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME) VALUES ('Leo','Capri');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME) VALUES ('Tom','Hanks');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME) VALUES ('Jim','Carrey');


INSERT INTO PHONENUMBER (NUMBER,IS_ACTIVE,TYPE,CUSTOMER_ID) VALUES ('111-111-111',false,'HOME',1);
INSERT INTO PHONENUMBER (NUMBER,IS_ACTIVE,TYPE,CUSTOMER_ID) VALUES ('222-222-222',false,'WORK',1);

INSERT INTO PHONENUMBER (NUMBER,IS_ACTIVE,TYPE,CUSTOMER_ID) VALUES ('333-333-333',false,'HOME',2);
INSERT INTO PHONENUMBER (NUMBER,IS_ACTIVE,TYPE,CUSTOMER_ID) VALUES ('444-444-444',false,'WORK',2);

INSERT INTO PHONENUMBER (NUMBER,IS_ACTIVE,TYPE,CUSTOMER_ID) VALUES ('555-555-555',false,'HOME',3);
INSERT INTO PHONENUMBER (NUMBER,IS_ACTIVE,TYPE,CUSTOMER_ID) VALUES ('666-666-666',false,'WORK',3);

INSERT INTO PHONENUMBER (NUMBER,IS_ACTIVE,TYPE,CUSTOMER_ID) VALUES ('777-777-777',false,'HOME',4);
INSERT INTO PHONENUMBER (NUMBER,IS_ACTIVE,TYPE,CUSTOMER_ID) VALUES ('888-888-888',false,'WORK',4);
INSERT INTO PHONENUMBER (NUMBER,IS_ACTIVE,TYPE,CUSTOMER_ID) VALUES ('999-999-999',false,'MOBILE',4);