openapi: 3.0.0
info:
  title: Phone Bank - OpenAPI 3.0
  description: |-
    This is a Phone Bank Service based on the OpenAPI 3.0 specification.  

  termsOfService: http://swagger.io/terms/
  contact:
    email: rangasanju@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://belong.phonebank.swagger.io/api/v1
tags:
  - name: Customer
    description: Customer Information
  - name: PhoneNumber
    description: Phone numbers for a customer
paths:

  /phone-bank/phone-numbers:
    get:
      tags:
        - PhoneNumber
      summary: Returns all phone numbers
      description: Returns all phone numbers
      operationId: getPhoneNumbers

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    allOf:
                      - properties:
                          phoneNumbers:
                            type: array
                            items:
                              $ref: '#/components/schemas/PhoneNumber'
                      - $ref: '#/components/schemas/PaginationResponse'

        '400':
          description: Bad Request


  /phone-bank/updateActivation/{phoneNumberId}:
    put:
      tags:
        - PhoneNumber
      summary: Activate / Deactivate a phone number
      description: Activate / Deactivate a phone number
      operationId: updateActivation
      parameters:
        - name: phoneNumberId
          in: path
          description: phone id to be activated / deactivated
          required: true
          schema:
            type: string

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  phonenumber:
                    $ref: '#/components/schemas/PhoneNumber'

        '400':
          description: Invalid ID supplied
        '404':
          description: Phone number not found



  /customer/phone-numbers/{customerId}:
    get:
      tags:
        - Customer
      summary: Returns all phone numbers for a given customer id
      description: Returns all phone numbers for a given customer id
      operationId: getPhoneNumbersById
      parameters:
        - name: customerId
          in: path
          description: ID of the customer
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    properties:
                      customer:
                        $ref: '#/components/schemas/Customer'

        '400':
          description: Invalid ID supplied
        '404':
          description: Customer not found


components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100000
        firstName:
          type: string
          example: Tom
        lastName:
          type: string
          example: Hanks
        phoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/PhoneNumber'
      xml:
        name: customer

    PhoneNumber:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100000
        phoneNumber:
          type: string
          example: 111-222-333
        active:
          type: boolean
      xml:
        name: phonenumber

    PaginationResponse:
      type: object
      properties:
        totalrecords:
          type: number
        displayrecords:
          type: number
